// @ts-check
// Sidebar wird automatisch aus der Ordnerstruktur in docs/ erzeugt.
// Reihenfolge: Nummern-Präfixe (01-, 02-, ...) und _category_.json / sidebar_position.
// Docs: https://docusaurus.io/docs/sidebar

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  handbuchSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
